### ISSUE TITLE
Improve python/pip executable selection

### ISSUE THREAD

**Issue by chrisjsewell** [marvel-nccr/ansible-role-bigdft#7]
In #6 a bug was fixed whereby `Installer.py` was being run on an unspecified python executable.
We now install the dependencies for both python2 and python3, which works but is not ideal and should be improved

**Comment by adegomme** [comment]
I tried to switch everything to python3 to avoid having both versions. There's a (temporary) issue with a python2 script used to compare output of tests, so I left it out for now and used mpirun directly.
I published it as v1.3.0. Please tell me if it seems ok for you.

**Comment by chrisjsewell** [comment]
This is now fixed with the new installer I believe
